# Site settings
title: Introduction to hashes in Ruby
header-img: img/home-bg.png
email: marin.cabac@gmail.com
copyright_name: marin-cabac
description: > # this means to ignore newlines until "baseurl:"
   Rubber Duck Debugging
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  marin-cabac
learn_profile: marin-cabac
email_username: marin.cabac@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
